services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: reis1x
      POSTGRES_PASSWORD: reis1x
      POSTGRES_DB: productsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - products-network

  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: products-api
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:postgresql://postgres:5432/productsdb
      QUARKUS_DATASOURCE_USERNAME: reis1x
      QUARKUS_DATASOURCE_PASSWORD: reis1x
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - products-network

volumes:
  postgres-data:

networks:
  products-network:
    driver: bridge
